server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/absenceManagerEnsah?useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      format_sql: true


